// [ ** AUTOGENERATED ** ]
// Copyright (c) 2001 - 2008 by Content Management AG, Cologne, Germany
// http://www.cm4all.com
// All rights reserved
var _xmn_=[
'wpfghkpgf',
'',
'%26YNaPCOG%26',
'%26RTQFWEVaKF%26',
'%26NCPIWCIG%26',
'%26EQWPVT%5B%26'];
__y(_xmn_);
function __y(l0) { 
var re = /\+/gi;
var l7='u'.charCodeAt(0);
var l8='\\'.charCodeAt(0);
for ( var l1=0;(l1<l0.length) ;l1++){
var l3='';
var l4=unescape(l0[l1].replace(re, ' '));
for (var l2=0;l2<l4.length;l2++){
var l5=(l4.charCodeAt(l2))-2;
var l6;
if (l5==l8 && l1 < l0.length+5 && (l4.charCodeAt(l2+1)) - 2 == l7) {
eval('l6 = "\\u' + l4.substring(l2+2,l2+6) + '";');
l2+=5;
} else if (l5==l8 && l1 < l0.length && (l4.charCodeAt(l2+1)) - 2 == l8) {
l6='\\';
l2+=1;
} else if (l5<=0)
l6=String.fromCharCode(l5+255);
else 
l6=String.fromCharCode(l5);
l3+=l6;
}
l0[l1]=l3;
}
}

I0:{if (!((typeof (window.top.wlFooterUrl)
)!=_xmn_[0] && window.top.wlFooterUrl!=_xmn_[1])) break I0;
{
wlUrl=window.top.wlFooterUrl;
wlUrl=wlUrl.replace(_xmn_[2],prodDef.wl_name);
wlUrl=wlUrl.replace(_xmn_[3],prodDef.product);
wlUrl=wlUrl.replace(_xmn_[4],localeDef.language);
wlUrl=wlUrl.replace(_xmn_[5],localeDef.country);
IMPORT_JS(wlUrl);
}

}

